Fix use of deprecated syscall() on macOS 10.12+.
syscall() was deprecated in 10.12 so replace syscall(SYS_gettid) with pthread_threadid_np(), available since 10.6. This returns the same value as the tid displayed in Xcode.

SYS_gettid on macOS also has a different meaning to Linux, documented as returning the "per-thread override identity", producing a uid and gid as output. See https://opensource.apple.com/source/xnu/xnu-4570.1.46/bsd/kern/kern_prot.c

util/virthread.c:272:17: error: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Werror,-Wdeprecated-declarations]
    pid_t tid = syscall(SYS_gettid);
                ^